version: "3.3"
services:
  waterfall:
    container_name: waterfall
    # Use a proper commit hash for specific deployments.
    image: ghcr.io/matrix-org/waterfall:sha-b64edee
    network_mode: host
    restart: always
    environment:
      # Set the `CONFIG` to the configuration you want.
      CONFIG: |
        homeserverurl: "http://localhost:8008"
        userid: "@sfu:shadowfax"
        accesstoken: "..."
        timeout: 30
