schema = 3

[mod]
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/pion/datachannel"]
    version = "v1.5.2"
    hash = "sha256-9/fNbx2t+gBvxt1YrtKWjTLw84opkYJj30iuca/72S4="
  [mod."github.com/pion/dtls/v2"]
    version = "v2.1.3"
    hash = "sha256-q0hG8PU3ddx7gGYOR5MgMMHxMme8y1ucCKY10jpuuuI="
  [mod."github.com/pion/ice/v2"]
    version = "v2.2.3"
    hash = "sha256-WuPdX8gFsNg+y5WhA5PK09aM0a5rP1bVE45BrB6/3sg="
  [mod."github.com/pion/interceptor"]
    version = "v0.1.10"
    hash = "sha256-pyAVtpy/vGj4bu05fTHb5936y9FCFhHMhSZJ26L3/Wo="
  [mod."github.com/pion/logging"]
    version = "v0.2.2"
    hash = "sha256-e/RKIPmZ6w3CehT7YzpAJLI65tcANZv82XfMXgJDXoU="
  [mod."github.com/pion/mdns"]
    version = "v0.0.5"
    hash = "sha256-iulRjqSG250x7rcrom1blS3qe35tvwwb2dmBAJslJDE="
  [mod."github.com/pion/randutil"]
    version = "v0.1.0"
    hash = "sha256-jl6WfLPH7RV5MQhQtqwSDzhIL0D0eCnDT2L9uButveI="
  [mod."github.com/pion/rtcp"]
    version = "v1.2.9"
    hash = "sha256-ZzZtckCIauxU6qbtI9F0em90TdU9EjKDn1STZXqrQRc="
  [mod."github.com/pion/rtp"]
    version = "v1.7.13"
    hash = "sha256-9btm2UrkABVnkRetVJl4imUTu761nX41QvOqWeWOvik="
  [mod."github.com/pion/sctp"]
    version = "v1.8.2"
    hash = "sha256-ydoPCOMtDire9jMZSJosDCpxT+ymGzkIwB5PjlQB/dE="
  [mod."github.com/pion/sdp/v3"]
    version = "v3.0.4"
    hash = "sha256-J/8BD0xiljqj/ZbXynsoQESxhKiMypcqMFwOCtguzfw="
  [mod."github.com/pion/srtp/v2"]
    version = "v2.0.5"
    hash = "sha256-8NmB8gi7ac+lSBRwU3lNi/S2G8+dIkKa/5Ll366UAnY="
  [mod."github.com/pion/stun"]
    version = "v0.3.5"
    hash = "sha256-uJlIgyWo1xzYm6V4G+oslxXMVPCm7ZAxy7ZfawUpczs="
  [mod."github.com/pion/transport"]
    version = "v0.13.0"
    hash = "sha256-cExHnHc3RuivvVzznxN8Sg9AQmV7Amy8hxxvWiX8xdY="
  [mod."github.com/pion/turn/v2"]
    version = "v2.0.8"
    hash = "sha256-93uGE08HjuXYmgtZO8ri9rSWriMq7tcwCMp/Ok9MtIM="
  [mod."github.com/pion/udp"]
    version = "v0.1.1"
    hash = "sha256-d5pN2N0bJnGlmxyFCYhVOatdW2Y5B21X176VMC1STRU="
  [mod."github.com/pion/webrtc/v3"]
    version = "v3.1.31"
    hash = "sha256-q5IdBwUQE8iryeeGwcT2GtiY5MGi/UHUy0pWAh0BUS8="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/thoas/go-funk"]
    version = "v0.9.2"
    hash = "sha256-At/z4HfE4mmRjAX5lAaY9QqHhTJHtTW7aCNf7clLVcg="
  [mod."github.com/tidwall/gjson"]
    version = "v1.14.1"
    hash = "sha256-v8zb6n6ReFE9hmiwT7tu4avTgLCrelD9lDMMg2My/AI="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.4"
    hash = "sha256-Y26Yf4u/GitvqI75f5oucCew6sQjxjRNo77ab58ofVw="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220622213112-05595931fe9d"
    hash = "sha256-2c4wvwiQ0DJSJsApfmNoxCxx1siRCiJvW9hhrGlcvds="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20221114191408-850992195362"
    hash = "sha256-c+XgCaUjF338r0C4LW0IMptBGHDo+X6c/urRDnQMwR0="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220624214902-1bab6f366d9e"
    hash = "sha256-LKDxEsF5v+SorAzHZGCjcY5dnpZMixI54NqapJy5jtY="
  [mod."golang.org/x/sys"]
    version = "v0.1.0"
    hash = "sha256-nZbEJ/2PuWrDLD4ujeVvcFGoIsfVoIH/Lcp4FjD7hpU="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."maunium.net/go/mautrix"]
    version = "v0.0.0-20221213094344-43c13b516216"
    hash = "sha256-U9AbPXp3N2NDRw3sWK1G7UGuvOfan3uou1RReCnOceY="
    replaced = "github.com/matrix-org/mautrix-go"
